// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {provider} from '../models';
import {cleaner} from '../models';
import {agent} from '../models';
import {main} from '../models';
import {rules} from '../models';
import {scanner} from '../models';

export function AIProvider():Promise<provider.Config>;

export function BuildCleanPlan(arg1:cleaner.BuildRequest):Promise<cleaner.Plan>;

export function CancelScan(arg1:string):Promise<void>;

export function CleanHistory():Promise<Array<cleaner.Result>>;

export function CleaningAgentPresets():Promise<Array<agent.Preset>>;

export function Dashboard():Promise<main.Dashboard>;

export function ExecuteCleanPlan(arg1:cleaner.ExecuteRequest):Promise<cleaner.Result>;

export function OpenSystemSettings(arg1:string):Promise<void>;

export function Rules():Promise<Array<rules.Rule>>;

export function RunCleaningAgent(arg1:agent.Request):Promise<agent.Result>;

export function SaveAIProvider(arg1:provider.ConfigInput):Promise<provider.Config>;

export function ScanFolders(arg1:string):Promise<Array<scanner.Folder>>;

export function ScanItems(arg1:string,arg2:number,arg3:number):Promise<scanner.ItemPage>;

export function ScanJob(arg1:string):Promise<scanner.Job>;

export function SelectScanDirectory():Promise<string>;

export function StartScan(arg1:scanner.Request):Promise<scanner.Job>;

export function TestAIProvider(arg1:provider.ConfigInput):Promise<provider.TestResult>;
