// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIProvider() {
  return window['go']['main']['App']['AIProvider']();
}

export function BuildCleanPlan(arg1) {
  return window['go']['main']['App']['BuildCleanPlan'](arg1);
}

export function CancelScan(arg1) {
  return window['go']['main']['App']['CancelScan'](arg1);
}

export function CleanHistory() {
  return window['go']['main']['App']['CleanHistory']();
}

export function CleaningAgentPresets() {
  return window['go']['main']['App']['CleaningAgentPresets']();
}

export function Dashboard() {
  return window['go']['main']['App']['Dashboard']();
}

export function ExecuteCleanPlan(arg1) {
  return window['go']['main']['App']['ExecuteCleanPlan'](arg1);
}

export function OpenSystemSettings(arg1) {
  return window['go']['main']['App']['OpenSystemSettings'](arg1);
}

export function RuleStatistics() {
  return window['go']['main']['App']['RuleStatistics']();
}

export function Rules() {
  return window['go']['main']['App']['Rules']();
}

export function RunCleaningAgent(arg1) {
  return window['go']['main']['App']['RunCleaningAgent'](arg1);
}

export function SaveAIProvider(arg1) {
  return window['go']['main']['App']['SaveAIProvider'](arg1);
}

export function ScanFolders(arg1) {
  return window['go']['main']['App']['ScanFolders'](arg1);
}

export function ScanItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanItems'](arg1, arg2, arg3);
}

export function ScanJob(arg1) {
  return window['go']['main']['App']['ScanJob'](arg1);
}

export function SelectScanDirectory() {
  return window['go']['main']['App']['SelectScanDirectory']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function SyncRules() {
  return window['go']['main']['App']['SyncRules']();
}

export function TestAIProvider(arg1) {
  return window['go']['main']['App']['TestAIProvider'](arg1);
}
